version: '2.13'
services:
 app:
   image: 'reto-2-devops-master:latest'
   build:
     context: .
     dockerfile: Dockerfile
   restart: always
   ports:
     - 8081:8081
   volumes:
     - ./app:/reto2